name: Coveralls

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  coveralls:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build and Test with Gradle
      run: ./gradlew build
      
    - name: jacoco
      run: ./gradlew jacocoTestCoverageVerification

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
